version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge # SQL Server för Mac (ARM/Intel)
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    container_name: devtools-sqlserver

volumes:
  sqlserver-data: